CREATE TABLE IF NOT EXISTS characters (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    lore TEXT,
    image_url VARCHAR(255)
);

INSERT INTO characters (name, role, lore, image_url) VALUES
       ('Geralt', 'Witcher', 'Geralt was born as the son of the sorceress Visenna and presumably, the warrior Korin. Shortly after his birth, his mother left him with the School of the Wolf at the stronghold of Kaer Morhen. There, Geralt was made and trained to become a Witcher. As a child, he was subjected to the Trial of The Grasses. crude, pragmatic, and cynical. Life has been unkind to Geralt, and left him shackled by self-doubt and uncertainty. He is burdened with scruples, and constantly questions the morality of his work: questions that do not stop even when he is called upon to slay violent bandits and marauding beasts.', 'https://img.odcdn.com.br/wp-content/uploads/2021/05/016.jpg'),
       ('Cirilla', 'Princess', 'Cirilla Fiona (better known as Ciri), was born in 1252 or 1253, and most likely during the Belleteyn holiday. She was the sole princess of Cintra, the daughter of Pavetta and Emhyr (who was using the alias "Duny" at the time) as well as Queen Calanthes granddaughter. Brave, determined, and a little naive. Ciri had a princess upbringing, and some of the facts of common peoples lives are a mystery to her. But she is unflagging in the pursuit of her goal, and even when surrounded by soldiers and powerful magics, she will fight back until the last of her strength is gone.', 'https://readysteadycut.com/wp-content/uploads/2023/06/the-witcher-season-3-poster-freya-allan-social-featured.jpg'),
       ('Yennefer', 'Witcher', 'Yennefer of Vengerberg is a powerful sorceress, the true love and soul mate of Geralt of Rivia, and a mother figure to Princess Ciri. A native of Vengerberg, the capital city of the kingdom of Aedirn, she was born with a congenital hunchback. willful and intelligent. Yennefer prizes her freedom above all else, and sees her power as a way to achieve that. She craves respect, even adoration, but she will never say so, instead brushing people off dismissively.', 'https://i.pinimg.com/736x/c4/4c/9f/c44c9f2b70cb9198bbfa754052f9c335.jpg'),
       ('Batman', 'Punisher', 'batman features him swearing vengeance against criminals after witnessing the murder of his parents Thomas and Martha as a child, a vendetta tempered with the ideal of justice. He trains himself physically and intellectually, crafts a bat-inspired persona, and monitors the Gotham streets at night.', 'https://img2.hulu.com/user/v3/artwork/2ce6365a-46e7-43d9-8d77-5b84753a663c?base_image_bucket_name=image_manager&base_image=99f4361c-662b-4693-89d7-7519197f9c40&size=458x687&format=webp'),
       ('Joker', 'Psycho', 'The Jokers main characteristic is his apparent insanity, although he is not described as having any particular psychological disorder. Like a psychopath, he lacks empathy, a conscience, and concern over right and wrong. The Joker is noted for his clownlike appearance and sick humour. The Joker, initially portrayed as a small-time crook, was disfigured and driven insane by an accident with toxic chemicals.', 'https://oyster.ignimgs.com/wordpress/stg.ign.com/2018/07/Heath-Ledger-Joker.jpg'),
       ('Michael', 'Manager', 'He is often considered a goofy boss by the employees of Dunder Mifflin. He is often the butt of everybodies jokes. Michael constantly tries to intermix his work life with his social life by inviting employees of Dunder Mifflin to come over house or get coffee. His introverted sensing supports his extroverted feeling, and he ends up trying to take care of his co-workers based on his past experiences', 'https://miro.medium.com/v2/resize:fit:620/1*RpQjmNQ-ORXkQaOX7zlbZw.png');